// src/utils/fontawesome.ts
/**
 * Font Awesome Configuration and Setup
 * 
 * Configures Font Awesome icons for the application
 */
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTicket,
  faUser,
  faCalendarDays,
  faSignInAlt,
  faUserPlus,
  faSignOutAlt,
  faBars,
  faTimes,
  faCrown,
  faEye,
  faLocationDot,
  faUsers,
  faEuroSign,
  faMusic,
  faLaptopCode,
  faTheaterMasks,
  faMicrophone,
  faCamera,
  faWineGlass,
  faShieldAlt,
  faCreditCard,
  faCalendarCheck,
  faGlobe,
  faArrowRight,
  faPlay,
  faStar,
  faMapMarkerAlt,
  faHeart,
  faShare,
  faBookmark,
  faFilter,
  faSearch,
  faSort,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faHome,
  faEnvelope,
  faPhone,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faSpinner,
  faDownload,
  faUpload,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faRefresh,
  faCog,
  faQuestionCircle,
  faBell,
  faComments,
  faUserFriends,
  faCalendar,
  faClock,
  faMoneyBillWave,
  faHandshake,
  faAward,
  faTrophy,
  faMedal,
  faGift,
  faFire,
  faThumbsUp,
  faThumbsDown,
  faLightbulb,
  faRocket,
  faMagic,
  faGem,
  faPalette,
  faImage,
  faVideo,
  faVolumeUp,
  faHeadphones,
  faBroadcastTower,
  faWifi,
  faDatabase,
  faCloud,
  faServer,
  faCode,
  faTerminal,
  faBug,
  faTools,
  faWrench,
  faHammer,
  faScrewdriver,
  faCogs,
  faLock,
  faUnlock,
  faKey,
  faFingerprint,
  faIdCard,
  faCertificate,
} from '@fortawesome/free-solid-svg-icons';

import {
  faHeart as faHeartRegular,
  faBookmark as faBookmarkRegular,
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
  faComments as faCommentsRegular,
  faThumbsUp as faThumbsUpRegular,
  faThumbsDown as faThumbsDownRegular,
  faEye as faEyeRegular,
  faFileAlt,
  faCopy,
  faEdit as faEditRegular,
  faTrashAlt,
  faFolder,
  faFolderOpen,
  faFile,
  faFileCode,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFileArchive,
  faImage as faImageRegular,
  faImages,
  faPlayCircle,
  faPauseCircle,
  faStopCircle,
  faCircle,
  faSquare,
  faStar as faStarRegular,
  faFlag,
  faPaperPlane,
  faShareSquare,
  faAddressCard,
  faIdBadge,
  faBuilding,
  faKeyboard,
  faHandPointer,
  faHandPaper,
  faHandRock,
  faHandPeace,
  faHandSpock,
  faHandLizard,
  faHandScissors,
  faLightbulb as faLightbulbRegular,
  faGem as faGemRegular,
  faMoneyBillAlt
} from '@fortawesome/free-regular-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faTicket,
  faUser,
  faCalendarDays,
  faSignInAlt,
  faUserPlus,
  faSignOutAlt,
  faBars,
  faTimes,
  faCrown,
  faEye,
  faLocationDot,
  faUsers,
  faEuroSign,
  faMusic,
  faLaptopCode,
  faTheaterMasks,
  faMicrophone,
  faCamera,
  faWineGlass,
  faShieldAlt,
  faCreditCard,
  faCalendarCheck,
  faGlobe,
  faArrowRight,
  faPlay,
  faStar,
  faMapMarkerAlt,
  faHeart,
  faShare,
  faBookmark,
  faFilter,
  faSearch,
  faSort,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faHome,
  faEnvelope,
  faPhone,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faSpinner,
  faDownload,
  faUpload,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faRefresh,
  faCog,
  faQuestionCircle,
  faBell,
  faComments,
  faUserFriends,
  faCalendar,
  faClock,
  faMoneyBillWave,
  faHandshake,
  faAward,
  faTrophy,
  faMedal,
  faGift,
  faFire,
  faThumbsUp,
  faThumbsDown,
  faLightbulb,
  faRocket,
  faMagic,
  faGem,
  faPalette,
  faImage,
  faVideo,
  faVolumeUp,
  faHeadphones,
  faBroadcastTower,
  faWifi,
  faDatabase,
  faCloud,
  faServer,
  faCode,
  faTerminal,
  faBug,
  faTools,
  faWrench,
  faHammer,
  faScrewdriver,
  faCogs,
  faLock,
  faUnlock,
  faKey,
  faFingerprint,
  faIdCard,
  faCertificate,

  // Regular icons
  faHeartRegular,
  faBookmarkRegular,
  faUserRegular,
  faEnvelopeRegular,
  faCalendarRegular,
  faClockRegular,
  faCommentsRegular,
  faThumbsUpRegular,
  faThumbsDownRegular,
  faEyeRegular,
  faFileAlt,
  faCopy,
  faEditRegular,
  faTrashAlt,
  faFolder,
  faFolderOpen,
  faFile,
  faFileCode,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFileArchive,
  faImageRegular,
  faImages,
  faPlayCircle,
  faPauseCircle,
  faStopCircle,
  faCircle,
  faSquare,
  faStarRegular,
  faFlag,
  faPaperPlane,
  faShareSquare,
  faAddressCard,
  faIdBadge,
  faBuilding,
  faKeyboard,
  faHandPointer,
  faHandPaper,
  faHandRock,
  faHandPeace,
  faHandSpock,
  faHandLizard,
  faHandScissors,
  faLightbulbRegular,
  faGemRegular,
  faMoneyBillAlt
);

// Configure Font Awesome
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

// Prevent Font Awesome from adding its CSS since we'll import it manually
config.autoAddCss = false;